name: blog project

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, mysql
          coverage: none

      - name: Dependency install
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress

      - name: config env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate
  
      - name: Set up database
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -h 127.0.0.1 --port 8888 -u root -p -e 'CREATE DATABASE IF NOT EXISTS blog;'
  
      - name: Run migrations
        run: php artisan migrate

      - name: Feature test
        run: php artisan test
